### ISSUE TITLE
Breadcrumb title i18n issue

### ISSUE THREAD

**Issue by Amerr** [poteto/ember-crumbly#69]
import { translationMacro as t } from "ember-i18n";

  breadCrumb: {
    title:  t('settings.language'),
  }

Error: Uncaught Error: Assertion Failed: Cannot translate settings.language. [object Object] does not have an i18n.

**Comment by abhilashlr** [comment]
If I understand ember-i18n, translationMacro from ember-i18n is a translation Computed property. You might have to use it as

```
breadCrumb: {
   title: this.i18n.t('settings.language')
}
```

**Comment by abhilashlr** [comment]
@poteto we can close this issue as it isn't related to crumbly

**Comment by fsmanuel** [comment]
@abhilashlr I think we can come up with a good solution to this problem. Setting the title in the route is not nice cause you have to set it in all you controllers. I guess a `i18nKey` is a good idea. I'll put some thought into this cause I'm facing the same issue.

**Comment by mrkirchner** [comment]
Anything come about this?  

`breadCrumb: {
   title: this.i18n.t('settings.language')
}`

This doesn't work because .t is undefined.  Seems that the service is injected after i forked the project added i18n to addon and implemented a new property localizationTitle but probably not the best solution.

**Comment by fsmanuel** [comment]
@mrkirchner use a computed property:

```js
breadCrumb: computed(function() {
  let i18n = get(this, 'i18n');
  return { title: i18n.t('settings.language') };
})
```
